Portfolio: mobile version (3rd part)
fbclh/portfolio-microverse pull request #4
Opened 2021-11-30 22:45 UTC by fbclh

* Add a contact form to the project and the portfolio of my partner
* Follow all the instructions for best practice and requirements

2021-11-30 23:11 UTC, andersonlebon requested changes
Hi @fbclh 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your form is working properly :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your design is perfect :clap: :100: :heavy_check_mark: 
## Required Changes ♻️
- [ ] Kindly check comments under the review.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 23:11 UTC, andersonlebon commented on index.html
> +            <button type="submit" class="btn">Get in touch</button>
- [ ] I think it would be nice if you add some styling interactions to this button. you can follow the template design
![Screenshot from 2021-11-30 21-48-21](https://user-images.githubusercontent.com/65068771/144117387-32a24bd6-1178-4175-99c5-5352ccde98ab.png)

2021-12-01 01:17 UTC, fbclh commented
Hello and thanks for your feedback! I have made the changes based on your feedback.

- Added all styling interactions state to the form button

2021-12-01 01:42 UTC, carlos-ssh approved these changes
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @fbclh , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 01:49 UTC, merged